def load(program, robot):

    @program(1, "Route")
    def route_program():
        robot.set_gyro_use(True)
        robot.motor_until_stalled(robot.right_motor, speed=-300)
        robot.set_drivebase_settings(turn_rate=100)
        robot.straight(790)
        robot.turn(87)
        robot.straight(40)
        robot.motor_angle(robot.right_motor, speed=300, angle=75)
        robot.wait(200)
        robot.straight(-15)
        robot.motor_angle(robot.right_motor, speed=-300, angle=80)
        robot.straight(95)
        robot.straight(-100)
        robot.turn(34)
        robot.straight(30)
        robot.motor_until_stalled(robot.right_motor, speed=100)
        robot.set_drivebase_settings(turn_rate=300, straight_speed=500)
        robot.straight(-40)
        robot.turn(50)
        robot.straight(600)

    @program(2, "tEAM")
    def motor_program():
        robot.set_gyro_use(True)
        robot.motor_until_stalled(robot.right_motor, speed=-300)
        robot.straight(840)
        robot.set_drivebase_settings(turn_rate=100)
        robot.turn(62)
        robot.straight(330)
        robot.motor_angle(robot.right_motor, speed=1000, angle=80)
        robot.motor_angle(robot.right_motor, speed=-100, angle=80)
        robot.straight(-50)
        robot.turn(-16)
        robot.straight(85)
        robot.motor_angle(robot.right_motor, speed=1000, angle=80)
        robot.motor_angle(robot.right_motor, speed=-100, angle=80)
        robot.set_drivebase_settings(turn_rate=300, straight_speed=500)
        robot.straight(-355)
        robot.turn(-55)
        robot.straight(-686)

    @program(3, "just run pls")
    def last_program():
        robot.set_drivebase_settings(straight_speed=350)
        robot.set_gyro_use(True)
        robot.motor_until_stalled(robot.right_motor, speed=500)
        robot.straight(1500)
        robot.turn(25)
        robot.straight(500)
        robot.turn(-25)
        robot.straight(160)
        robot.set_drivebase_settings(straight_speed=500)
        robot.straight(-600)
        robot.turn(-35)
        robot.straight(-300)
        robot.turn(40)
        robot.straight(-300)
        robot.turn(70)
        robot.straight(-280)
        robot.turn(-75)
        robot.straight(-750)

    @program(4, "Blink")
    def blink_program():
        while True:
            robot.hub.display.pixel(2, 2, 100)
            robot.wait(250)
            robot.hub.display.pixel(2, 2, 0)
            robot.wait(250)

