def load(program, robot):

    @program(1, "setup")
    def setupmotor():
        robot.motor_target(robot.right_motor, 300, 45)
        robot.motor_target(robot.left_motor, 300, 0)
        robot.wait(2000)
        
    @program(2, "betterGamble")
    def bettergamble():
        robot.reset_drivebase_settings()
        robot.set_drivebase_settings(800)
        robot.set_gyro_use(True)
        robot.straight(-10)
        robot.reset_heading(0)
        robot.set_gyro_use(True)
        
        robot.reset_heading(0)
        robot.straight(850)
        robot.motor_angle(robot.right_motor, 300, -300)
        robot.straight(55)
        robot.motor_angle(robot.right_motor, 800, -360)
        robot.straight(-850)
    
    @program(3, "DerErsteRun?!")
    def route_program():
        robot.set_gyro_use(True)
        robot.set_drivebase_settings(800)
        robot.straight(410)
        robot.straight(-410)
        robot.straight(30)
        robot.turn(46)
        robot.motor_until_stalled(robot.right_motor, -300)
        robot.straight(540)
        robot.motor_angle(robot.right_motor, speed=300, angle=130)
        robot.set_drivebase_settings(straight_speed=800)
        robot.straight(-500)
    
    @program(4, "Drohnenfiech")
    def drohnenfiech():
        robot.set_gyro_use(True)
        robot.set_drivebase_settings(450)
        robot.reset_heading(0)
        robot.straight(720)
        robot.turn(-30)
        robot.straight(10)
        robot.turn(-20)
        robot.turn(50)
        robot.straight(-180)
        robot.turn(-50)
        robot.straight(630)
        robot.turn(-35)
        robot.straight(85)
        robot.turn(65)
        robot.straight(-30)
        robot.turn(13)
        robot.set_drivebase_settings(800)
        robot.straight(20)
        robot.reset_drivebase_settings()
        robot.motor_angle(robot.right_motor, 300, 100)
        robot.straight(-80)
        robot.motor_angle(robot.left_motor, 300, -60)
        robot.motor_angle(robot.right_motor, 300, -100)
        robot.straight(65)
        robot.motor_angle(robot.left_motor, 300, 60)
        robot.straight(-30)
        robot.turn(-42)
        robot.straight(250)
        robot.set_drivebase_settings(80)
        robot.straight(140)
        robot.straight(-65)
        robot.turn(-100)
        
    @program(5, "weisses Ding")
    def route_program():
        robot.motor_target(robot.right_motor, 500, -10)
        robot.wait(5000)
        robot.set_drivebase_settings(550)
        robot.straight(-10)
        robot.reset_heading(0)
        robot.straight(800)
        robot.straight(-80)
        robot.straight(50)
        robot.wait(200)
        robot.straight(-20)
        robot.turn(135)
        robot.straight(-150)
        robot.turn(-50)
        robot.straight(215)
        robot.turn(-10)
        robot.motor_angle(robot.right_motor, 600, -60)
        robot.turn(20)
        robot.turn(-10)
        robot.motor_angle(robot.right_motor, 600, 60)
        robot.straight(-180)
        robot.turn(70)
        robot.straight(680)


    @program(6, "altePalme")
    def altePalme():
        robot.motor_target(robot.right_motor, 600, -60)
        robot.wait(3000)
        robot.set_gyro_use(True)
        robot.straight(-10)
        robot.reset_heading(0)
        robot.set_drivebase_settings(800)
        robot.straight(300)
        robot.motor_angle(robot.right_motor, 300, 40)
        robot.straight(80)
        robot.motor_angle(robot.right_motor, 200, -55)
        robot.straight(-120)
        robot.motor_angle(robot.right_motor, 300, 55)
        robot.straight(-200)
