from pybricks.parameters import Direction, Port

LEFT_ATTACHMENT_PORT = Port.A
RIGHT_ATTACHMENT_PORT = Port.B
LEFT_DRIVE_PORT = Port.C
RIGHT_DRIVE_PORT = Port.D
FORCE_SENSOR_PORT = Port.F

LEFT_DRIVE_DIRECTION = Direction.COUNTERCLOCKWISE
RIGHT_DRIVE_DIRECTION = Direction.CLOCKWISE

WHEEL_DIAMETER_MM = 62.4
AXLE_TRACK_MM = 80

DEFAULT_STRAIGHT_SPEED = 450
DEFAULT_STRAIGHT_ACCELERATION = 700
DEFAULT_TURN_RATE = 100
DEFAULT_TURN_ACCELERATION = 300

DEFAULT_DRIVEBASE_SETTINGS = (
    DEFAULT_STRAIGHT_SPEED,
    DEFAULT_STRAIGHT_ACCELERATION,
    DEFAULT_TURN_RATE,
    DEFAULT_TURN_ACCELERATION,
)


MOTION_POLL_MS = 10
MOTION_START_GUARD_MS = 30
MOTION_MIN_PROGRESS_DEG = 0.5
MOTION_MIN_PROGRESS_MM = 2
DRIVE_TIMEOUT_MS = 20000
MOTOR_TIMEOUT_MS = 10000

STRAIGHT_BRAKE_REACTION_MS = 20
STRAIGHT_MIN_BRAKE_LEAD_MM = 3
STRAIGHT_BRAKE_SETTLE_MS = 50
STRAIGHT_COMPLETION_TOLERANCE_MM = 15

TURN_POSITION_TOLERANCE_DEG = 1
TURN_BRAKE_LEAD_DEG = 1.7
TURN_COMPLETION_TOLERANCE_DEG = 2
TURN_CORRECTION_ATTEMPTS = 2
TURN_CORRECTION_TIMEOUT_MS = 4000

TURN_COMPENSATION_DEG = 6
TURN_BRAKE_SETTLE_MS = 120
TURN_LOG_INTERVAL_MS = 250

# Ein-Pass-Drehung; Startwerte auf der Wettkampfmatte prüfen.
SMOOTH_TURN_MAX_RATE = 160       # Grad pro Sekunde
SMOOTH_TURN_MIN_RATE = 28        # kleinste zuverlässige Dauerdrehung
SMOOTH_TURN_DECEL = 450         # Grad pro Sekunde zum Abbremsen
SMOOTH_TURN_STOP_DELAY_MS = 20  # Reaktionszeit und passives Bremsen
SMOOTH_TURN_STOP_OFFSET_DEG = 0.35
SMOOTH_TURN_BRAKE_DECEL = 1800  # effektiver Wert aus sechs Hub-Messungen
SMOOTH_TURN_SETTLE_MS = 90
SMOOTH_TURN_SETTLE_TIMEOUT_MS = 400
SMOOTH_TURN_STOP_RATE_DEG_S = 5
SMOOTH_TURN_STOP_STABLE_MS = 30
SMOOTH_TURN_ACCEPT_DEG = 1.0
SMOOTH_TURN_STALL_MS = 600       # Zeit ohne messbaren Drehfortschritt
SMOOTH_TURN_STALL_PROGRESS_DEG = 0.5
SMOOTH_TURN_DEBUG = False

STALL_TIMEOUT_MS = 6000
STALL_PROGRESS_WINDOW_MS = 400
STALL_MIN_PROGRESS_DEG = 3
STALL_MIN_PROGRESS_RATIO = 0.10

TELEMETRY_SAMPLE_MS = 20
TELEMETRY_MAX_BYTES = 180000
